---

- name: Check if drawio already installed
  command: which drawio
  register: which_drawio
  changed_when: false
  failed_when: false

- name: Install draw.io dependencies
  become: true
  package:
    name:
      - libgtk-3-0
      - libnotify4
      - libnss3
      - libxss1
      - libxtst6
      - xdg-utils
      - libatspi2.0-0
      - libuuid1
      - libappindicator3-1
      - libsecret-1-0
      - libgbm1
      - libasound2
  when: which_drawio.rc != 0

- name: "Install drawio {{ drawio_version }}"
  become: true
  apt:
    deb: https://github.com/jgraph/drawio-desktop/releases/download/v{{ drawio_version }}/drawio-amd64-{{ drawio_version }}.deb
  when: which_drawio.rc != 0
