---

- name: Install essential tools
  become: true
  ansible.builtin.package:
    name:
      - git
      - make
      - cmake
      - unzip
      - wget
  when: install_essential_tools

- name: Evaluate cmake install prefix  # noqa fqcn
  shell: |
    cd /tmp \
    && rm -rf /tmp/docmake \
    && git clone https://github.com/langchr86/docmake.git \
    && cmake -L docmake/CMakeLists.txt | grep CMAKE_INSTALL_PREFIX | cut -d "=" -f2 \
    && cd /tmp \
    && rm -rf /tmp/docmake
  register: cmake_install_prefix
  changed_when: false

- name: Install docmake modules  # noqa fqcn
  become: true
  shell: |
    cd /tmp \
    && rm -rf /tmp/docmake \
    && git clone https://github.com/langchr86/docmake.git \
    && cd docmake \
    && git checkout {{ docmake_version }} \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make install \
    && cd /tmp \
    && rm -rf /tmp/docmake
  args:
    creates: "{{ cmake_install_prefix.stdout }}/lib/cmake/docmake/helpers.cmake"

- import_tasks: tasks/texlive_min.yml # noqa fqcn
  when: texlive_min

- import_tasks: tasks/texlive_additional.yml  # noqa fqcn
  when: texlive_additional

- import_tasks: tasks/metropolis.yml  # noqa fqcn
  when: metropolis

- import_tasks: tasks/tikz_uml.yml  # noqa fqcn
  when: tikz_uml

- import_tasks: tasks/drawio.yml  # noqa fqcn
  when: drawio

- import_tasks: tasks/gpp.yml # noqa fqcn
  when: gpp

- import_tasks: tasks/markdownlint.yml  # noqa fqcn
  when: markdownlint

- import_tasks: tasks/pandoc.yml  # noqa fqcn
  when: pandoc

- name: Additional packages
  become: true
  ansible.builtin.package:
    name: "{{ additional_packages }}"
