---

- name: Install essential tools
  become: true
  ansible.builtin.package:
    name:
      - git
      - make
      - cmake
      - unzip
      - wget
  when: install_essential_tools

- name: Evaluate cmake install prefix
  ansible.builtin.shell: |
    cd /tmp \
    && rm -rf /tmp/docmake \
    && git clone https://github.com/langchr86/docmake.git \
    && cmake -L docmake/CMakeLists.txt | grep CMAKE_INSTALL_PREFIX | cut -d "=" -f2 \
    && cd /tmp \
    && rm -rf /tmp/docmake
  register: cmake_install_prefix
  changed_when: false

- name: Install docmake modules
  become: true
  ansible.builtin.shell: |
    cd /tmp \
    && rm -rf /tmp/docmake \
    && git clone https://github.com/langchr86/docmake.git \
    && cd docmake \
    && git checkout {{ docmake_version }} \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make install \
    && cd /tmp \
    && rm -rf /tmp/docmake
  args:
    creates: "{{ cmake_install_prefix.stdout }}/lib/cmake/docmake/helpers.cmake"

- ansible.builtin.import_tasks: tasks/texlive_min.yml
  when: texlive_min

- ansible.builtin.import_tasks: tasks/texlive_additional.yml
  when: texlive_additional

- ansible.builtin.import_tasks: tasks/metropolis.yml
  when: metropolis

- ansible.builtin.import_tasks: tasks/tikz_uml.yml
  when: tikz_uml

- ansible.builtin.import_tasks: tasks/drawio.yml
  when: drawio

- ansible.builtin.import_tasks: tasks/gpp.yml
  when: gpp

- ansible.builtin.import_tasks: tasks/markdownlint.yml
  when: markdownlint

- ansible.builtin.import_tasks: tasks/pandoc.yml
  when: pandoc

- name: Additional packages
  become: true
  ansible.builtin.package:
    name: "{{ additional_packages }}"
