---

- name: Install essential tools
  become: yes
  package: name="{{ item }}"
  with_items:
    - git
    - make
    - cmake
    - unzip
    - wget

- name: Evaluate cmake install prefix
  shell: |
    cd /tmp \
    && rm -rf /tmp/docmake \
    && git clone https://github.com/langchr86/docmake.git \
    && cmake -L docmake/CMakeLists.txt | grep CMAKE_INSTALL_PREFIX | cut -d "=" -f2 \
    && cd /tmp \
    && rm -rf /tmp/docmake
  register: cmake_install_prefix
  changed_when: False

- name: Install docmake modules
  become: yes
  shell: |
    cd /tmp \
    && rm -rf /tmp/docmake \
    && git clone https://github.com/langchr86/docmake.git \
    && cd docmake \
    && git checkout {{ docmake_version }} \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make install \
    && cd /tmp \
    && rm -rf /tmp/docmake
  args:
    creates: "{{ cmake_install_prefix.stdout }}/lib/cmake/docmake/helpers.cmake"

- import_tasks: tasks/texlive_min.yml
  when: texlive_min

- import_tasks: tasks/texlive_additional.yml
  when: texlive_additional

- import_tasks: tasks/metropolis.yml
  when: metropolis

- import_tasks: tasks/tikz_uml.yml
  when: tikz_uml

- import_tasks: tasks/drawio.yml
  when: drawio

- import_tasks: tasks/gpp.yml
  when: gpp

- import_tasks: tasks/markdownlint.yml
  when: markdownlint

- import_tasks: tasks/pandoc.yml
  when: pandoc

- name: Additional packages
  become: yes
  package: name="{{ item }}"
  with_items:
    "{{ additional_packages }}"
