---

- include_tasks: tasks/nodejs.yml

- command: which npm
  register: which_npm
  changed_when: false
  failed_when: false

- name: Install npm for markdownlint
  become: true
  package:
    name: npm
  when: which_npm.rc != 0

# https://github.com/igorshubovych/markdownlint-cli
- name: Install markdownlint
  become: true
  npm:
    name: markdownlint-cli
    global: true
    version: "{{ markdownlint_version }}"
