---

- ansible.builtin.include_tasks: tasks/nodejs.yml

- ansible.builtin.command: which npm
  register: which_npm
  changed_when: false
  failed_when: false

- name: Install npm for markdownlint
  become: true
  ansible.builtin.package:
    name: npm
  when: which_npm.rc != 0

# https://github.com/igorshubovych/markdownlint-cli
- name: Install markdownlint
  become: true
  community.general.npm:
    name: markdownlint-cli
    global: true
    version: "{{ markdownlint_version }}"
