---

- name: Install FiraSans
  become: yes
  shell: |
    cd /tmp
    mkdir fira
    cd fira
    wget https://github.com/bBoxType/FiraSans/archive/master.zip
    unzip master.zip
    mkdir -p /usr/share/fonts/opentype/fira
    mkdir -p /usr/share/fonts/truetype/fira
    find FiraSans-master/ -name "*.otf" -exec cp {} /usr/share/fonts/opentype/fira/ \;
    find FiraSans-master/ -name "*.ttf" -exec cp {} /usr/share/fonts/truetype/fira/ \;
    cd /tmp
    rm -rf /tmp/fira
  args:
    creates: /usr/share/fonts/opentype/fira/FiraCode-Regular.otf

- name: Install metropolis theme
  become: yes
  shell: |
    cd /tmp
    mkdir metropolis
    cd metropolis
    git clone https://github.com/matze/mtheme.git
    cd mtheme
    git checkout v1.2
    make sty
    make install
    cd /tmp
    rm -rf /tmp/metropolis
  args:
    creates: /usr/share/texlive/texmf-dist/tex/latex/beamertheme-metropolis/beamerthememetropolis.sty
