---

- name: Check if node.js already installed
  ansible.builtin.command: which node
  register: which_node
  changed_when: false
  failed_when: false

- name: Install curl for node.js installation
  become: true
  ansible.builtin.package:
    name: curl
  when: which_node.rc != 0

- name: Download and prepare node.js (deb)
  become: true
  ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_{{ nodejs_version }}.x | bash -
  when: which_node.rc != 0 and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: Download and prepare node.js (rpm)
  become: true
  ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_{{ nodejs_version }}.x | bash -
  when: which_node.rc != 0 and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- name: "Install node.js {{ nodejs_version }}"
  become: true
  ansible.builtin.package:
    name: nodejs
  when: which_node.rc != 0
