---

- name: Install minimal needed latex tools
  become: yes
  apt:
    install_recommends: no
    name:
      - texlive-base
      - texlive-pictures
      - texlive-latex-recommended

- name: Install latin modern latex packet
  become: yes
  package:
    name: lmodern
