---

- name: Install additional latex tools
  become: yes
  apt:
    name: "{{ item }}"
    install_recommends: no
  with_items:
    - texlive-plain-generic
    - texlive-fonts-extra
    - texlive-lang-english
    - texlive-lang-german
    - texlive-science
    - texlive-xetex
    - texlive-extra-utils
    - latexmk
