---

- name: Install additional latex tools
  become: yes
  apt:
    install_recommends: no
    name:
      - texlive-plain-generic
      - texlive-fonts-extra
      - texlive-lang-english
      - texlive-lang-german
      - texlive-science
      - texlive-xetex
      - texlive-extra-utils
      - latexmk
