---

- name: Install additional latex tools
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - texlive-plain-generic
      - texlive-fonts-extra
      - texlive-lang-english
      - texlive-lang-german
      - texlive-science
      - texlive-xetex
      - texlive-extra-utils
      - latexmk
