---

- name: Install minimal needed latex tools
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - texlive-base
      - texlive-pictures
      - texlive-latex-recommended

- name: Install latin modern latex packet
  become: true
  ansible.builtin.package:
    name: lmodern
