---
- hosts: localhost

  pre_tasks:
    - name: Update package manager repositories
      become: yes
      package: update_cache=yes
      changed_when: false

  roles:
    - role: ansible-role-docmake
      vars:
        pandoc: on
        drawio: on
        gpp: on
        markdownlint: on
        metropolis: on
        texlive_additional: on
        texlive_min: on
        tikz_uml: on
        additional_packages:
          - make
          - cmake
