---
- hosts: localhost

  pre_tasks:
    - name: Update package manager repositories
      become: true
      package: update_cache=yes
      changed_when: false

  roles:
    - role: ansible-role-docmake
      vars:
        pandoc: true
        drawio: true
        gpp: true
        markdownlint: true
        metropolis: true
        texlive_additional: true
        texlive_min: true
        tikz_uml: true
        additional_packages:
          - make
          - cmake
