name: ansible_run

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu-bionic
          - ubuntu-focal
          - ubuntu-jammy
          - debian-buster

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install podman
        run: |
          sudo apt install podman

      - name: System information
        run: |
          uname -a
          lsb_release -a
          podman --version

      - name: Prepare and run container
        run: |
          ./testing/1_create.sh ${{matrix.distro}}
          ./testing/2_run.sh ${{matrix.distro}}

      - name: Test ansible
        run: |
          podman exec test-container /etc/ansible/roles/ansible-role-docmake/testing/4_test.sh --idempotence

      - name: Cleanup
        run: |
          ./testing/5_remove.sh
